import * as BOARD_CONFIG from "./board";

const DROPPER_CANVAS_WIDTH = BOARD_CONFIG.BOARD_CANVAS_WIDTH;
const DROPPER_CANVAS_HEIGHT = BOARD_CONFIG.BOARD_CANVAS_HEIGHT;
const GLASS_WIDTH = 160;
const GLASS_HEIGHT = 160;
const RADIUS = GLASS_WIDTH / 2;
const BORDER_WIDTH = 10;
const CENTER_SQUARE_COLOR = "#fff";
const BORDER_OUTER_WIDTH = 8;
const BORDER_INNER_WIDTH = 8;
const BORDER_INNER = RADIUS - BORDER_INNER_WIDTH;
const RECT_SIZE = 8;
const STROKE_COLOR = "#efefef";
const INNER_STROKE_COLOR = "#efefef";
const OUTER_STROKE_COLOR = "#efefef";

export {
  DROPPER_CANVAS_WIDTH,
  DROPPER_CANVAS_HEIGHT,
  GLASS_WIDTH,
  GLASS_HEIGHT,
  RADIUS,
  BORDER_WIDTH,
  CENTER_SQUARE_COLOR,
  BORDER_OUTER_WIDTH,
  BORDER_INNER_WIDTH,
  BORDER_INNER,
  RECT_SIZE,
  STROKE_COLOR,
  INNER_STROKE_COLOR,
  OUTER_STROKE_COLOR,
};
