import * as BOARD_CONFIG from "./board";

const DROPPER_INITIAL_WIDTH = BOARD_CONFIG.BOARD_INITIAL_WIDTH;
const DROPPER_INITIAL_HEIGHT = BOARD_CONFIG.BOARD_INITIAL_HEIGHT;
const GLASS_WIDTH = 160;
const GLASS_HEIGHT = 160;
const RADIUS = GLASS_WIDTH / 2;
const BORDER_WIDTH = 10;
const CENTER_SQUARE_COLOR = "#000";
const BORDER_OUTER_WIDTH = 8;
const BORDER_INNER_WIDTH = 8;
const BORDER_INNER = RADIUS - BORDER_INNER_WIDTH;
const RECT_SIZE = 10;
const RECT_LINE_WIDTH = 1;
const STROKE_COLOR = "#efefef";
const INNER_STROKE_COLOR = "#efefef";
const OUTER_STROKE_COLOR = "#efefef";

export {
  DROPPER_INITIAL_WIDTH,
  DROPPER_INITIAL_HEIGHT,
  GLASS_WIDTH,
  GLASS_HEIGHT,
  RADIUS,
  BORDER_WIDTH,
  CENTER_SQUARE_COLOR,
  BORDER_OUTER_WIDTH,
  BORDER_INNER_WIDTH,
  BORDER_INNER,
  RECT_SIZE,
  RECT_LINE_WIDTH,
  STROKE_COLOR,
  INNER_STROKE_COLOR,
  OUTER_STROKE_COLOR,
};
