import * as BOARD_CONFIG from "./board";

const DROPPER_CANVAS_WIDTH = BOARD_CONFIG.BOARD_CANVAS_WIDTH;
const DROPPER_CANVAS_HEIGHT = BOARD_CONFIG.BOARD_CANVAS_HEIGHT;
const RADIUS = 50;
const BORDER_WIDTH = 8;
const CENTER_SQUARE_COLOR = "#fff";
const BORDER_OUTER_WIDTH = 4;
const BORDER_INNER_WIDTH = 6;
const BORDER_INNER = 46;
const RECT_SIZE = 10;
const STROKE_COLOR = "#efefef";
const INNER_STROKE_COLOR = "#efefef";
const OUTER_STROKE_COLOR = "#efefef";
const DRAW_SIZE = Math.floor(RADIUS + BORDER_WIDTH / 2);
const RECT_COUNT = Math.ceil(Math.sqrt(2 * DRAW_SIZE));

export {
  DROPPER_CANVAS_WIDTH,
  DROPPER_CANVAS_HEIGHT,
  RECT_COUNT,
  RADIUS,
  BORDER_WIDTH,
  CENTER_SQUARE_COLOR,
  BORDER_OUTER_WIDTH,
  BORDER_INNER_WIDTH,
  BORDER_INNER,
  RECT_SIZE,
  STROKE_COLOR,
  INNER_STROKE_COLOR,
  OUTER_STROKE_COLOR,
  DRAW_SIZE,
};
